version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # location of package.json
    schedule:
      interval: "weekly" # daily, weekly, monthly
    commit-message:
      prefix: "chore(deps)"
